<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WLMT.Bungalows.Application\WLMT.Bungalows.Application.csproj" />
    <ProjectReference Include="..\WLMT.Bungalows.Infrastructure\WLMT.Bungalows.Infrastructure.csproj" />
  </ItemGroup>

</Project>
